# Notebook 07: tuples, function lingo, functions that return tuples
by Rachel Langgin \\
March 2022 and July 2024 \\
Haverford College and University of Nevada, Las Vegas \\

# Goals
* Learn the trick for adding cells
* You get the "modern" style of for loop comfortably ensconced in your brain
* We tackle tuples together
* We practice lingo of functions and using tuples

## How do I add a cell without going to the insert menu?

esc-a adds a cell above, esc-b adds a cell below

## Some other tricks:

esc-dd deletes a cell
esc-m makes a cell markdown

## Review:
    

In [ ]:
x = [1,7,10,20, 37]
for y in x:
    print(y)

1
7
10
20
37


In [ ]:
x = [1,7,10,20, 37]
for y in x:
    print(x)

[1, 7, 10, 20, 37]
[1, 7, 10, 20, 37]
[1, 7, 10, 20, 37]
[1, 7, 10, 20, 37]
[1, 7, 10, 20, 37]


In [ ]:
students = ["Sigourney", "Meredith", "Chung-pei", "Geraldo", "Tuck"]
for student in students:
    print(student)

Sigourney
Meredith
Chung-pei
Geraldo
Tuck


In [ ]:
students = ["Sigourney", "Meredith", "Chung-pei", "Geraldo", "Tuck"]
j=472
for student in students:
    j+=1
    print("%d %s %d" %(j, student, 1))
# We added that "1" in class as a way to understand what the "%d" was doing.

473 Sigourney 1
474 Meredith 1
475 Chung-pei 1
476 Geraldo 1
477 Tuck 1


In [ ]:
def add10(x):
    return(x+10)
y=14
samantha=42
print(add10(y))
print(add10(100))
print(add10(samantha))

24
110
52


When I define a function as above, "x" is called the argument to the function.  When I actually call the function as in "add10(100)" 100 is the thing I'm passing to the function.

In [ ]:
import numpy as np
x = np.array([1,5,7,10,20]) # creating an array called x
somenumbers = np.array([22, 32, 42, 52, 62])  # creating another array
# called somenumbers
i = np.where((x > 6) & (x<15))
print(i)   # this will print out row numbers, indices, that meet your criterion
print(somenumbers[i])   # print the elements of the array that correspond to those indices

(array([2, 3]),)
[42 52]


In [ ]:
print(x[i]) # if you

[ 7 10]


Describe what right ascension is.
Describe what declination is.
Why would restricting redshift to a number between .3 and .4 (for example) give you a "slice" of the universe?

## Tuples

I'll just tell you, I'm a little scared of tuples.  I got myself unscared last year, but let's see how I do.  They're extremely similar to lists.  For now, the big difference will be that you use parentheses instead of square brackets. (So for now, the difference is cosmetic.)

In [ ]:
# Here's a tuple
# The parentheses make it a tuple
tup1=(1,2,3)

In [ ]:
tup2=(4,5,6)

When you add two tuples together, they concatenate.

In [ ]:
stuff = tup2+tup1
stuff

(4, 5, 6, 1, 2, 3)

Notice the result has parentheses around it, which means it's a tuple.

Tuple items are indexed, just like lists and arrays.  You can look at the 0th item by using square brackets and specifying '0' like this:

In [ ]:
stuff[3]

1

In [ ]:
tup1[0]

1

IMHO here's where it gets interesting....

You can have a tuple of lists.  In tup3, each item of the tuple is a list. (You can tell it's a list because it's in square brackets.)

In [ ]:
tup3=([1,2,3],[4,5,6])

So now what do you think tup3[0] is?

In [ ]:
tup3[0]

[1, 2, 3]

(Here's a space for you to put some notes about what happened there. Talk to your neighbor about it.)




So can I index that list?  Indeed you can.  If you want the 1st item in the 0th list, you say...

In [ ]:
tup3[0][1]

2

And here's the 2nd item in the 1st list.

In [ ]:
tup3[1][2]

6

(Write some more notes to yourself here.)

In [ ]:
# a tuple of tuples
trees = [("sycamore", "willow", "oak", "maple"), ("pine", "dogwood")]

In [ ]:
trees

[('sycamore', 'willow', 'oak', 'maple'), ('pine', 'dogwood')]

In [ ]:
trees[0][2]

'oak'

## At this point we just started thinking about the weirdest things we could do
Here's one. This is a list that contains two numpy arrays, and then its third element is a list of tuples.  Crazy.

In [ ]:
listofarrays = [np.array([1,3,5]),np.array([7,10,14]),trees]

In [ ]:
listofarrays

[array([1, 3, 5]),
 array([ 7, 10, 14]),
 [('sycamore', 'willow', 'oak', 'maple'), ('pine', 'dogwood')]]

You can actually do this same thing with lists.  Above we made a tuple of lists.  But we can also make a list of lists. (The difference is that the list is created with square brackets and the tuple is created with parentheses.) At this point, the difference is cosmetic, but they do have different properties (that we're not getting to today.)

In [ ]:
# We create two lists
# (The square brackets make them lists)
list1=[15,225,4722]
list2=[17,-24, 82]


In [ ]:
# Just like tuples, when you add them, they concatenate
list1+list2

[15, 225, 4722, 17, -24, 82]

Notice the result has square brackets around it, which means it's a list.

I can also make a list of lists.  In the following list1 is the zeroth item in list3, and list2 is the 1st item in list3.

In [ ]:
list3=[list1, list2]
list3

[[15, 225, 4722], [17, -24, 82]]

So what if I want the 2nd item in the 0th list?

In [ ]:
list3[0][2]

4722

Now you try one.  How do you specify the 1st(not the zeroth but the first) item in the 0th list?

In [ ]:
list3[0][1]

225

## So now finally, when we want to use the output list of numbers from an np.where command, why do we need to put a [0] around the output?
Because np.where returns a tuple, and we only want the first item.

You can actually put the [0] on the line where you call np.where, if you want.  Like this...

In [ ]:
x=np.arange(100,300,10) # Create an array of numbers from 100 to 300, counting by 10
myfavoriteindices = np.where(x>200)

In [ ]:
x

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290])

In [ ]:
x[myfavoriteindices[0]]

array([210, 220, 230, 240, 250, 260, 270, 280, 290])

In [ ]:
x

## Great big disclaimer.  I got through several years of programming in python before I could actually explain why you sometimes need that [0] after np.where.  And even now, I'm not particularly comfortable with it.  The point is, you don't actually have to understand everything like that, you just have to know enough to know what to try.

# Now we need to practice defining and calling functions and "passing" things to them.
A function is sort of like a list of instructions that the computer will do when you "pass" it something to actually do them on.  Like a stapler is a function that puts a staple in a batch of papers. But it's kind of useless until you pass it a bunch of papers.

# My assignment to myself
Define a function that takes two arguments, a string and a number.
The function should return a tuple that consists of three items, the string, the number, the number of characters in the string, and the product of the number and the number of characters in the string.
Pass "hello" and "4" to the function.


In [ ]:
def weird(x,y):  # define a function weird that returns the same
    # string and number you gave it, and also the number of characters
    # in that string, and the produce of the number you gave it times
    # the number of characters in the string
    mytuple=(x,y,len(x),y*len(x))
    return(mytuple)

In [ ]:
# First let's try just calling weird
weird("haverford", 10) # Calling the function weird

('haverford', 10, 9, 90)

Notice it returns a tuple. (You can tell because it has parentheses around it.)

If you only want one piece of the tuple there are several ways to go about it.

### Method 1

In [ ]:
weirdout = weird("hello",4)  #Setting the output of weird("hello", 4)
# equal to weirdout so that I can use weirdout for things
weirdout

('hello', 4, 5, 20)

So now weirdout is set to be that tuple.

In [ ]:
# So if we just want the 3rd item in the tuple we say
weirdout[3]

20

### Method 2
You can accomplish the same thing all in one line by saying....

In [ ]:
weird("hello",4)[3]

20

So that "[3]" at the end of the call to weird, tells it we only want the 3rd item in the tuple that it returns.

(Make a couple notes for yourself here.  Ask your neighbors some questions.)



### Method 3

I think this one is my favorite because it doesn't seem like it should work. Check this out....

In [ ]:
firstarg, secondarg, nletters, product = weird("hello", 4)

I knew I was getting 4 items in the tuple, so I put 4 things on the left side of the equals sign.

In [ ]:
firstarg

'hello'

In [ ]:
secondarg

4

In [ ]:
nletters

5

In [ ]:
product

20

Please note that you could call those 4 things anything you wanted.

Write yourself some notes here.

# Coding assignment #1
Define a function that has two arguments x and y
The function should *return* a tuple with three items: the first is the product of the two numbers, the 2nd is x/y, and the 3rd is y/x.
Pass two numbers to the function and make sure it works.  Try it with a variety of inputs.

In [ ]:
def anotherfunction(x,y):
    mytuple=(x*y, x/y, y/x)
    return(mytuple)

In [ ]:
print(anotherfunction(4,7))  # Pass 4 and 7 to the function

(28, 0.5714285714285714, 1.75)


# Coding assignment #2
This is an exercise that will let you practice using tuples and function.  

Step 1: Create 2 functions:
* one that takes two arguments and returns a tuple with two items: the first is the product of the two arguments, and the second is the quotient of the two arguments
* create a function that take one argument, and returns that argument+10

Step 2: Use a combination of the two functions you just created to multiply two numbers together and add 10.  For added bonus points, do this all on one line.


In [ ]:
# Step 1

In [ ]:
def funreturn(x,y):
    mytuple=(x*y, x/y)
    return(mytuple)

In [ ]:
def funprint(x,y):
    mytuple=(x*y, x/y)
    print(mytuple)

In [ ]:
def add10(x):
    return(x+10)

In [ ]:
# Step 2

In [ ]:
add10(funreturn(6,7)[0])

52